start-inventory:
	cd inventory && cargo run &
start-payment:
	cd payment && cargo run &
start-delivery:
	cd delivery && cargo run &
start-management:
	cd management && cargo run &
start-all: start-delivery start-inventory start-payment start-management

